let shopItemsData = [
    {
        id: "a1",
        name: "Casual Shirt",
        price: 45,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img-1.jpg",
      },
      {
        id: "a2",
        name: "Office Shirt",
        price: 100,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img-2.jpg",
      },
      {
        id: "a3",
        name: "T Shirt",
        price: 25,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img-3.jpg",
      },
      {
        id: "a4",
        name: "Mens Suit",
        price: 300,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img-4.jpg",
      },
      {
        id: "a5",
        name: "Mens Tie",
        price: 25,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img-5.png",
      },
      {
        id: "a6",
        name: "Casual shoes",
        price: 200,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img-6.png",
      },
      {
        id: "a7",
        name: "black suit",
        price: 450,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img-7.png",
      },
      {
        id: "a8",
        name: "polo shirt",
        price: 45,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img-8.png",
      },
      {
        id: "a9",
        name: "denim shirt",
        price: 85,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img-9.png",
      },
      {
        id: "a10",
        name: "denim pants",
        price: 120,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img-10.png",
      },
      {
        id: "a11",
        name: "basic cap",
        price: 35,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img-11.png",
      },
      {
        id: "a12",
        name: "leather boots",
        price: 350,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img-12.png",
      }
]